language: go

go:
  - "1.11.x"

addons:
  postgresql: "9.4" 

env:
  - DEP_VERSION="0.5.0"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

before_script:
  - psql -U postgres -d postgres -a -f ./test.sql

install:
  - dep ensure

script:
  - go test -v -race ./...