version: '3'
services: 
  frontend:
    build:
      context: .
      dockerfile: ./docker/Frontend.Dockerfile
    ports:
      - "8080:8080"
    links:
      - server

  server:
    build:
      context: .
      dockerfile: ./docker/Server.Dockerfile
    ports:
      - "3000:3000"
    links:
      - postgres

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"