version: '3'
services: 
  frontend:
    build:
      context: .
      dockerfile: ./docker/Frontend.Dockerfile
    ports:
      - "8080:8080"
    links:
      - server
    command: ["/wait-for-it.sh", "server:3000", "--", "nginx", "-g", "daemon off;"]

  server:
    build:
      context: .
      dockerfile: ./docker/Server.Dockerfile
    links:
      - postgres
    command: ["/wait-for-it.sh", "postgres:5432", "--", "./webserver"]

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}