version: '3'
services: 
  frontend:
    build:
      context: .
      dockerfile: ./docker/Frontend.Dockerfile
    ports:
      - "8080:8080"
    links:
      - server

  server:
    build:
      context: .
      dockerfile: ./docker/Server.Dockerfile
    ports:
      - "3000:3000"